version: '3'
services:
  bot:
    container_name: mybot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - cfg.env
    volumes:
      - ./${LOG_FILE}:/app/${LOG_FILE}
    command: python bot.py
