
name: TestCode

on:
  push:
    branches: [ "bot" ]
  pull_request:
    branches: [ "bot" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - uses: actions/checkout@v3
      - name: Run test
        run: pytest src/test_add_nums.py
